from backend.ai.base_provider import AIProvider
from backend.models.ai_reasoning import AIReasoning


class MockAIProvider(AIProvider):
    provider_name = "Mock AI Provider"

    def ask(self, prompt: str, context: str | None = None) -> AIReasoning:
        return AIReasoning(
            executive_summary=(
                "Atlas identified this as an investigation question. "
                "The analysis should compare brand visibility, feature associations, "
                "relationship strength, and ranked supporting evidence before reaching a conclusion."
            ),
            confidence="Medium",
            opportunities=[
                "Improve messaging around features competitors are more strongly associated with.",
                "Create content that directly answers the question users are asking AI systems.",
            ],
            risks=[
                "Current reasoning is generated by the mock provider.",
                "Real AI provider integration is still pending.",
            ],
            follow_up_questions=[
                "Which competitor has the strongest feature associations?",
                "What evidence supports this recommendation?",
                "How does this differ by AI model?",
            ],
            provider=self.provider_name,
        )